CREATE TABLE partida (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),  
    codigo VARCHAR(50) NOT NULL,  
    data_inicio TIMESTAMP NOT NULL, 
    data_fim TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE partida_videos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(), 
    partida_id UUID NOT NULL, 
    path VARCHAR(255) NOT NULL,  
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,  
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,  
    FOREIGN KEY (partida_id) REFERENCES partida(id) 
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO teste;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO teste;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO teste;